Repository kubernetes/kubeadm, pull requests merged in 2018-10, with the labels that each got.

#1148 e2e-docs: instruct about removing old x-on-y jobs
  docs/managing-e2e-tests.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#1173 Fix grammar errors in some warning messages in help_utils.py
  vagrant/hack/lib/help_utils.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1157 add an e2e test for verifying manifest lists
  tests/e2e/manifests/README.md
  tests/e2e/manifests/verify_manifest_lists.go
  tests/e2e/manifests/verify_manifest_lists.sh
  tests/e2e/manifests/verify_manifest_lists_test.go
Labels: approved, area/testing, cncf-cla: yes, kind/feature, lgtm, size/XL

#1187 Update box.md
  vagrant/box.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1195 Fix the wrong file name
  docs/design/design_v1.10.md
  docs/design/design_v1.8.md
  docs/design/design_v1.9.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
