Repository kubernetes/kubeadm, pull requests merged in 2018-06, with the labels that each got.

#879 Typo fix: netowrking -> networking
  vagrant/hack/ansible/roles/kubernetes-cni/tasks/calico.yml
  vagrant/hack/ansible/roles/kubernetes-cni/tasks/flannel.yml
  vagrant/hack/ansible/roles/kubernetes-cni/tasks/main.yml
  vagrant/hack/ansible/roles/kubernetes-cni/tasks/weavenet.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#891 Typo fix: explicitely -> explicitly
  docs/design/design_v1.10.md
  docs/design/design_v1.9.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#890 testing-pre-releases
  CONTRIBUTING.md
  testing-pre-releases.md
Labels: approved, area/UX, cncf-cla: yes, kind/documentation, lgtm, priority/important-soon, sig/cluster-lifecycle, size/XL

#913 kubeadm playground test pre-releases and v1alpha2 API
  vagrant/README.md
  vagrant/box.md
  vagrant/hack/ansible/filter_plugins/kube.py
  vagrant/hack/ansible/group_vars/all/main.yml
  vagrant/hack/ansible/prerequisites.yml
  vagrant/hack/ansible/roles/kubeadm-config/tasks/main.yml
  vagrant/hack/ansible/roles/kubeadm-config/templates/etc/kubernetes/kubeadm.conf.v1alpha1.yaml.j2
  vagrant/hack/ansible/roles/kubeadm-config/templates/etc/kubernetes/kubeadm.conf.v1alpha2.yaml.j2
  vagrant/hack/ansible/roles/kubeadm-config/vars/main.yml
  vagrant/hack/ansible/roles/kubernetes-packages/tasks/binary.yml
  vagrant/hack/ansible/roles/kubernetes-packages/tasks/debian.yml
  vagrant/hack/ansible/roles/kubernetes-packages/tasks/debian_package.yml
  vagrant/hack/ansible/roles/kubernetes-packages/tasks/main.yml
  vagrant/hack/ansible/roles/kubernetes-packages/tasks/redhat.yml
  vagrant/hack/ansible/roles/kubernetes-packages/vars/main.yml
  vagrant/hack/ansible/roles/kubernetes-vagrant/tasks/main.yml
  vagrant/hack/ansible/roles/kubernetes/README.md
  vagrant/hack/ansible/roles/kubernetes/tasks/debian.yml
  vagrant/hack/ansible/roles/kubernetes/tasks/main.yml
  vagrant/hack/lib/ansible_utils.py
  vagrant/hack/lib/kubernetes_utils.py
  vagrant/hack/lib/vagrant_utils.py
  vagrant/kubeadm-playground
  vagrant/spec/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#943 Typo fix: kubernets->kubernetes
  vagrant/hack/ansible/group_vars/all/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS
