Repository kubernetes/kubeadm, pull requests merged in 2018-04, with the labels that each got.

#746 fix grammar mistake
  docs/design/design_v1.10.md
  docs/design/design_v1.9.md
Labels: cncf-cla: yes, lgtm, size/S

#757 Typo fix in design_v1.9.md
  docs/design/design_v1.9.md
Labels: cncf-cla: yes, lgtm, size/S

#763 some typo fixes
  docs/design/design_v1.10.md
  docs/design/design_v1.8.md
  docs/design/design_v1.9.md
Labels: cncf-cla: yes, size/S

#764 Some small typo fixes
  docs/design/design_v1.7.md
  docs/design/design_v1.8.md
  docs/design/design_v1.9.md
Labels: cncf-cla: yes, lgtm, size/S

#774 Typo fix: does not exists->does not exist
  docs/design/design_v1.8.md
  docs/design/design_v1.9.md
Labels: cncf-cla: yes, size/XS
