Repository kubernetes/kubeadm, pull requests merged in 2018-05, with the labels that each got.

#780 Merge vagrant-kubeadm-testing for contributor experience
  CONTRIBUTING.md
  vagrant/.gitignore
  vagrant/README.md
  vagrant/Vagrantfile
  vagrant/copy_kubeadm_bin.sh
Labels: cncf-cla: yes, size/L

#777 Typo fix: boostrap->bootstrap
  docs/design/design_v1.10.md
  docs/design/design_v1.8.md
  docs/design/design_v1.9.md
Labels: cncf-cla: yes, size/XS

#781 Add certified-k8s logo for 1.10 and fix broken link for 1.9
  docs/design/design_v1.10.md
  docs/design/design_v1.9.md
Labels: cncf-cla: yes, lgtm, size/XS

#803 Update the packages publication verification script
  tests/e2e/README.md
  tests/e2e/pinned_releases.sh
  tests/e2e/pinned_rpms.sh
  tests/e2e/verify_packages_published.sh
Labels: cncf-cla: yes, lgtm, size/L

#824 Typo fix: recognise->recognize
  docs/design/design_v1.8.md
Labels: cncf-cla: yes, lgtm, size/XS

#823 contributing.md: add notes about website docs and unit tests
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/M

#795 kubeadm-contrib-ux
  vagrant/.gitignore
  vagrant/README.md
  vagrant/Vagrantfile
  vagrant/copy_kubeadm_bin.sh
  vagrant/kubeadm-playground
  vagrant/spec/README.md
  vagrant/spec/cluster.yml
  vagrant/spec/masters.yml
  vagrant/spec/nodes.yml
Labels: cncf-cla: yes, size/XL

#796 kubeadm-contrib-hack-lib
  vagrant/hack/lib/ansible-utils.rb
  vagrant/hack/lib/cluster-api.rb
  vagrant/hack/lib/kubeadm-options.rb
  vagrant/hack/lib/kubernetes-utils.rb
  vagrant/hack/lib/test-guide.rb
  vagrant/hack/lib/utils.rb
  vagrant/hack/lib/vagrant-utils.rb
Labels: cncf-cla: yes, size/XL

#869 update owners file
  OWNERS
Labels: cncf-cla: yes, lgtm, size/S

#862 small fixes and improvements on kubeadm-playground
  vagrant/README.md
  vagrant/box.md
  vagrant/hack/ansible/external-vip.yml
  vagrant/hack/ansible/roles/etcd/tasks/main.yml
  vagrant/hack/ansible/roles/external-ca/tasks/main.yml
  vagrant/hack/ansible/roles/kubeadm-config/tasks/main.yml
  vagrant/hack/ansible/roles/kubeadm-config/vars/main.yml
  vagrant/hack/ansible/roles/kubeadm-init/tasks/main.yml
  vagrant/hack/ansible/roles/kubeadm-join/tasks/main.yml
  vagrant/hack/ansible/roles/kubeadm-reset/tasks/main.yml
  vagrant/hack/ansible/roles/kubernetes-cni/tasks/main.yml
  vagrant/hack/ansible/roles/kubernetes-vip/tasks/main.yml
  vagrant/hack/ansible/roles/kubernetes-vip/vars/main.yml
  vagrant/hack/kubeadm-playground.rb
  vagrant/hack/lib/cluster_api.py
  vagrant/hack/lib/kubernetes_utils.py
  vagrant/hack/lib/vagrant_utils.py
  vagrant/kubeadm-playground
Labels: cncf-cla: yes, lgtm, size/L

#861 add SECURITY_CONTACTS file
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S
