Repository kubernetes/kubeadm, pull requests merged in 2018-09, with the labels that each got.

#1120 Enhanced code readability
  vagrant/hack/lib/ansible_utils.py
  vagrant/hack/lib/kubeadm_utils.py
  vagrant/hack/lib/vagrant_utils.py
  vagrant/kubeadm-playground
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/L

#1139 Update README.md
  vagrant/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#1140 Fix wrong link
  testing-pre-releases.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#1143 Update cluster_api.py
  vagrant/hack/lib/cluster_api.py
  vagrant/kubeadm-playground
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#1144 move verify_packages_published to it's own folder
  tests/e2e/README.md
  tests/e2e/packages/README.md
  tests/e2e/packages/verify_packages_published.sh
Labels: approved, area/testing, cncf-cla: yes, kind/cleanup, lgtm

#1138 add doc about managing e2e tests
  docs/managing-e2e-tests.md
Labels: approved, area/testing, cncf-cla: yes, kind/documentation, lgtm, priority/important-longterm, sig/cluster-lifecycle, size/L

#1149 OWNERS: add neolit123 to reviewers
  OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS
