Repository kubernetes/kubeadm, pull requests merged in 2018-08, with the labels that each got.

#1010 Disable swap in all nodes
  vagrant/hack/ansible/roles/common/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#993 add a note
  vagrant/hack/ansible/group_vars/all/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#996 Add instructions on updating command line reference docs
  CONTRIBUTING.md
  docs/updating-command-reference.md
Labels: approved, cncf-cla: yes, documentation/improvement, kind/documentation, lgtm, size/M

#1068 Fix some typos in messages
  vagrant/hack/lib/cluster_api.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#1075 Typo fix: trough->through
  docs/design/design_v1.10.md
  docs/design/design_v1.8.md
  docs/design/design_v1.9.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1073 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
