Repository kubernetes/kubeadm, pull requests merged in 2019-03, with the labels that each got.

#1441 Update embargo doc link in SECURITY_OWNERS and change PST to PSC
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#1446 Welcome kinder!
  kinder/README.md
  kinder/roadmap.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, priority/important-longterm, sig/cluster-lifecycle, size/L

#1459 move testing-pre-releases.md into docs folder
  docs/testing-pre-releases.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/backlog, sig/cluster-lifecycle, size/XS

#1457 Update kubeadm OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/backlog, sig/cluster-lifecycle, size/XS

#1467 Update CONTRIBUTING doc link to kinder README
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/backlog, sig/cluster-lifecycle, size/XS

#1450 kinder
  .gitignore
  go.mod
  kinder/.gitignore
  kinder/OWNERS
  kinder/README.md
  kinder/cmd/kinder/build/build.go
  kinder/cmd/kinder/build/nodevariant/nodevariant.go
  kinder/cmd/kinder/cp/cp.go
  kinder/cmd/kinder/create/cluster/createcluster.go
  kinder/cmd/kinder/create/create.go
  kinder/cmd/kinder/create/node/createnode.go
  kinder/cmd/kinder/do/do.go
  kinder/cmd/kinder/exec/exec.go
  kinder/cmd/kinder/kinder.go
  kinder/cmd/kinder/version/version.go
  kinder/doc/getting-started.md
  kinder/doc/prepare-for-tests.md
  kinder/doc/reference.md
  kinder/doc/test-HA.md
  kinder/doc/test-XonY.md
  kinder/doc/test-upgrades.md
  kinder/go.mod
  kinder/go.sum
  kinder/main.go
  kinder/pkg/actions/cluster-info.go
  kinder/pkg/actions/const.go
  kinder/pkg/actions/copy-certs.go
  kinder/pkg/actions/kubeadm-init.go
  kinder/pkg/actions/kubeadm-join.go
  kinder/pkg/actions/kubeadm-reset.go
  kinder/pkg/actions/kubeadm-upgrade.go
  kinder/pkg/actions/smoke-test.go
  kinder/pkg/actions/util.go
  kinder/pkg/build/alter/alter.go
  kinder/pkg/build/alter/bits.go
  kinder/pkg/build/alter/imageBits.go
  kinder/pkg/build/alter/kubeadmBits.go
  kinder/pkg/build/alter/upgradeBinaryBits.go
  kinder/pkg/cluster/actions.go
  kinder/pkg/cluster/actions_test.go
  kinder/pkg/cluster/context.go
  kinder/pkg/cluster/context_test.go
  kinder/pkg/cluster/etcd.go
  kinder/pkg/cluster/node.go
  kinder/roadmap.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, priority/important-longterm, sig/cluster-lifecycle, size/XXL
