Repository kubernetes/kubeadm, pull requests merged in 2020-02, with the labels that each got.

#2019 Fix some typos in release-cycle.md
  docs/release-cycle.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, priority/backlog, sig/cluster-lifecycle, size/XS

#2026 docs: Fix some typos
  kinder/doc/kind-kinder.md
Labels: approved, cncf-cla: yes, lgtm, sig/cluster-lifecycle, size/XS

#2032 Fix simple typo in testing-pre-releases.md
  docs/testing-pre-releases.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/cluster-lifecycle, size/XS

#2033 Replacing 'HTTP' by 'HTTPS' for securing links
  kinder/hack/verify-golint.sh
  kinder/hack/verify-staticcheck.sh
  operator/hack/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/cluster-lifecycle, size/XS
