Repository kubernetes/kubeadm, pull requests merged in 2021-12, with the labels that each got.

#2620 kinder: switch all workflows to containerd
  kinder/ci/tools/update-workflows/templates/workflows/discovery-tasks.yaml
  kinder/ci/tools/update-workflows/templates/workflows/external-ca-tasks.yaml
  kinder/ci/tools/update-workflows/templates/workflows/external-etcd-tasks.yaml
  kinder/ci/tools/update-workflows/templates/workflows/patches-tasks.yaml
  kinder/ci/tools/update-workflows/templates/workflows/presubmit-upgrade-latest.yaml
  kinder/ci/tools/update-workflows/templates/workflows/skew-x-on-y-tasks.yaml
  kinder/ci/tools/update-workflows/templates/workflows/upgrade-latest-no-addon-config-maps.yaml
  kinder/ci/tools/update-workflows/templates/workflows/upgrade-tasks.yaml
  kinder/ci/workflows/discovery-tasks.yaml
  kinder/ci/workflows/external-ca-tasks.yaml
  kinder/ci/workflows/external-etcd-tasks.yaml
  kinder/ci/workflows/patches-tasks.yaml
  kinder/ci/workflows/presubmit-upgrade-latest.yaml
  kinder/ci/workflows/skew-x-on-y-tasks.yaml
  kinder/ci/workflows/upgrade-latest-no-addon-config-maps.yaml
  kinder/ci/workflows/upgrade-tasks.yaml
  kinder/pkg/cluster/manager/actions/cluster-info.go
Labels: priority/important-soon, kind/cleanup, cncf-cla: yes, lgtm, area/test, size/M, sig/cluster-lifecycle, approved, area/kinder

#2624 .github/ISSUE_TEMPLATE: update to include CNI/CRI
  .github/ISSUE_TEMPLATE.md
Labels: cncf-cla: yes, lgtm, priority/important-longterm, size/XS, sig/cluster-lifecycle, approved, kind/documentation

#2606 Update ha-considerations.md
  docs/ha-considerations.md
Labels: cncf-cla: yes, lgtm, area/HA, size/L, sig/cluster-lifecycle, approved, kind/documentation, ok-to-test
