Repository kubernetes/kubeadm, pull requests merged in 2023-06, with the labels that each got.

#2886 Fix a bug in UpgradeAddonsBeforeControlPlane feature gate e2e test
  kinder/pkg/cluster/manager/actions/actions.go
  kinder/pkg/cluster/manager/actions/kubeadm-config.go
  kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go
Labels: cncf-cla: yes, lgtm, size/M, approved, area/kinder

#2885 add pacoxu to approvers
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2889 Add chendave to reviewer list
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2893 use pacoxu/actions-comment-on-issue@1.0.3
  .github/workflows/support-command.yaml
Labels: kind/bug, cncf-cla: yes, lgtm, size/XS, approved

#2895 kinder: use eks cluster in test-infra jobs
  kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-addons.yaml
  kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-discovery.yaml
  kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-dryrun.yaml
  kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-external-ca.yaml
  kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-external-etcd.yaml
  kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-kubelet-x-on-y.yaml
  kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-learner-mode.yaml
  kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-patches.yaml
  kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-rootless.yaml
  kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-upgrade-addons-before-controlplane.yaml
  kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-upgrade.yaml
  kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-x-on-y.yaml
  kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder.yaml
Labels: cncf-cla: yes, lgtm, priority/important-longterm, size/S, kind/feature, approved, area/kinder
